package ai.axhub.sdk;

import java.util.Map;

public final class ErrorCodes { private ErrorCodes() {} public static final Map<String, ErrorInfo> ALL = Map.ofEntries(
  Map.entry("already_accessed", new ErrorInfo("conflict", 409, false)),
  Map.entry("already_active", new ErrorInfo("conflict", 409, false)),
  Map.entry("already_deleted", new ErrorInfo("conflict", 409, false)),
  Map.entry("already_exists", new ErrorInfo("conflict", 409, false)),
  Map.entry("already_inactive", new ErrorInfo("conflict", 409, false)),
  Map.entry("already_member", new ErrorInfo("conflict", 409, false)),
  Map.entry("already_revoked", new ErrorInfo("conflict", 409, false)),
  Map.entry("already_settled", new ErrorInfo("conflict", 409, false)),
  Map.entry("already_suspended", new ErrorInfo("conflict", 409, false)),
  Map.entry("app_unavailable", new ErrorInfo("conflict", 409, false)),
  Map.entry("bad_request", new ErrorInfo("validation", 400, false)),
  Map.entry("cannot_reactivate", new ErrorInfo("conflict", 409, false)),
  Map.entry("conflict", new ErrorInfo("conflict", 409, false)),
  Map.entry("cross_tenant", new ErrorInfo("validation", 400, false)),
  Map.entry("domain_blocked", new ErrorInfo("precondition_failed", 422, false)),
  Map.entry("domain_taken", new ErrorInfo("conflict", 409, false)),
  Map.entry("duplicate", new ErrorInfo("validation", 400, false)),
  Map.entry("empty", new ErrorInfo("validation", 400, false)),
  Map.entry("forbidden", new ErrorInfo("permission_denied", 403, false)),
  Map.entry("internal_error", new ErrorInfo("internal", 500, false)),
  Map.entry("invalid_format", new ErrorInfo("validation", 400, false)),
  Map.entry("invalid_state_transition", new ErrorInfo("conflict", 409, false)),
  Map.entry("invalid_value", new ErrorInfo("validation", 400, false)),
  Map.entry("invitation_expired", new ErrorInfo("not_found", 410, false)),
  Map.entry("last_admin", new ErrorInfo("conflict", 409, false)),
  Map.entry("not_admin", new ErrorInfo("permission_denied", 403, false)),
  Map.entry("not_allowed", new ErrorInfo("validation", 400, false)),
  Map.entry("not_deleted", new ErrorInfo("conflict", 409, false)),
  Map.entry("not_found", new ErrorInfo("not_found", 404, false)),
  Map.entry("not_member", new ErrorInfo("permission_denied", 403, false)),
  Map.entry("not_suspended", new ErrorInfo("conflict", 409, false)),
  Map.entry("pending_exists", new ErrorInfo("conflict", 409, false)),
  Map.entry("permanently_deleted", new ErrorInfo("not_found", 410, false)),
  Map.entry("precondition_failed", new ErrorInfo("precondition_failed", 412, false)),
  Map.entry("required", new ErrorInfo("validation", 400, false)),
  Map.entry("schema_name_taken", new ErrorInfo("conflict", 409, false)),
  Map.entry("slug_taken", new ErrorInfo("conflict", 409, false)),
  Map.entry("temporarily_unavailable", new ErrorInfo("unavailable", 429, true)),
  Map.entry("token_expired", new ErrorInfo("unauthenticated", 401, true)),
  Map.entry("token_invalid", new ErrorInfo("unauthenticated", 401, true)),
  Map.entry("token_missing", new ErrorInfo("unauthenticated", 401, true)),
  Map.entry("too_long", new ErrorInfo("validation", 400, false))
); }
