package ai.axhub.sdk;

import java.util.List;

public final class Routes { private Routes() {} public static final List<Route> ALL = List.of(
  new Route("GET", "/.well-known/jwks.json", "Auth", "authGetWellKnownJwksJson"),
  new Route("GET", "/.well-known/oauth-authorization-server", "Auth", "authGetWellKnownOauthAuthorizationServer"),
  new Route("GET", "/.well-known/openid-configuration", "Auth", "authGetWellKnownOpenidConfiguration"),
  new Route("DELETE", "/api/v1/apps/{appID}", "Apps", "appsDeleteApiV1AppsByAppID"),
  new Route("GET", "/api/v1/apps/{appID}", "Apps", "appsGetApiV1AppsByAppID"),
  new Route("PATCH", "/api/v1/apps/{appID}", "Apps", "appsPatchApiV1AppsByAppID"),
  new Route("DELETE", "/api/v1/apps/{appID}/access", "Apps", "appsDeleteApiV1AppsByAppIDAccess"),
  new Route("POST", "/api/v1/apps/{appID}/access", "Apps", "appsPostApiV1AppsByAppIDAccess"),
  new Route("GET", "/api/v1/apps/{appID}/access/me", "Apps", "appsGetApiV1AppsByAppIDAccessMe"),
  new Route("POST", "/api/v1/apps/{appID}/archive", "Apps", "appsPostApiV1AppsByAppIDArchive"),
  new Route("GET", "/api/v1/apps/{appID}/comments", "Apps", "appsGetApiV1AppsByAppIDComments"),
  new Route("POST", "/api/v1/apps/{appID}/comments", "Apps", "appsPostApiV1AppsByAppIDComments"),
  new Route("GET", "/api/v1/apps/{appID}/db/tables", "Schema", "schemaGetApiV1AppsByAppIDDbTables"),
  new Route("GET", "/api/v1/apps/{appID}/db/tables/{table}/rows", "Schema", "schemaGetApiV1AppsByAppIDDbTablesByTableRows"),
  new Route("GET", "/api/v1/apps/{appID}/deployments", "Deploy", "deployGetApiV1AppsByAppIDDeployments"),
  new Route("POST", "/api/v1/apps/{appID}/deployments", "Deploy", "deployPostApiV1AppsByAppIDDeployments"),
  new Route("GET", "/api/v1/apps/{appID}/deployments/{did}", "Deploy", "deployGetApiV1AppsByAppIDDeploymentsByDid"),
  new Route("POST", "/api/v1/apps/{appID}/deployments/{did}/cancel", "Deploy", "deployPostApiV1AppsByAppIDDeploymentsByDidCancel"),
  new Route("POST", "/api/v1/apps/{appID}/deployments/{did}/rollback", "Deploy", "deployPostApiV1AppsByAppIDDeploymentsByDidRollback"),
  new Route("GET", "/api/v1/apps/{appID}/diagnosis", "Deploy", "deployGetApiV1AppsByAppIDDiagnosis"),
  new Route("GET", "/api/v1/apps/{appID}/env-vars", "Apps", "appsGetApiV1AppsByAppIDEnvVars"),
  new Route("POST", "/api/v1/apps/{appID}/env-vars", "Apps", "appsPostApiV1AppsByAppIDEnvVars"),
  new Route("PUT", "/api/v1/apps/{appID}/env-vars/{key}/staging-value", "Apps", "appsPutApiV1AppsByAppIDEnvVarsByKeyStagingValue"),
  new Route("DELETE", "/api/v1/apps/{appID}/git-connection", "Deploy", "deployDeleteApiV1AppsByAppIDGitConnection"),
  new Route("GET", "/api/v1/apps/{appID}/git-connection", "Deploy", "deployGetApiV1AppsByAppIDGitConnection"),
  new Route("PATCH", "/api/v1/apps/{appID}/git-connection", "Deploy", "deployPatchApiV1AppsByAppIDGitConnection"),
  new Route("POST", "/api/v1/apps/{appID}/git-connection", "Deploy", "deployPostApiV1AppsByAppIDGitConnection"),
  new Route("POST", "/api/v1/apps/{appID}/git/github/connect", "Deploy", "deployPostApiV1AppsByAppIDGitGithubConnect"),
  new Route("GET", "/api/v1/apps/{appID}/git/github/install/start", "Deploy", "deployGetApiV1AppsByAppIDGitGithubInstallStart"),
  new Route("DELETE", "/api/v1/apps/{appID}/likes", "Apps", "appsDeleteApiV1AppsByAppIDLikes"),
  new Route("POST", "/api/v1/apps/{appID}/likes", "Apps", "appsPostApiV1AppsByAppIDLikes"),
  new Route("GET", "/api/v1/apps/{appID}/likes/me", "Apps", "appsGetApiV1AppsByAppIDLikesMe"),
  new Route("GET", "/api/v1/apps/{appID}/logs", "Deploy", "deployGetApiV1AppsByAppIDLogs"),
  new Route("POST", "/api/v1/apps/{appID}/oauth-clients", "Auth", "authPostApiV1AppsByAppIDOauthClients"),
  new Route("POST", "/api/v1/apps/{appID}/promotions/{requestID}/retry", "Deploy", "deployPostApiV1AppsByAppIDPromotionsByRequestIDRetry"),
  new Route("DELETE", "/api/v1/apps/{appID}/raw-db", "Apps", "appsDeleteApiV1AppsByAppIDRawDb"),
  new Route("POST", "/api/v1/apps/{appID}/raw-db", "Apps", "appsPostApiV1AppsByAppIDRawDb"),
  new Route("GET", "/api/v1/apps/{appID}/releases", "Deploy", "deployGetApiV1AppsByAppIDReleases"),
  new Route("GET", "/api/v1/apps/{appID}/releases/promote-preflight", "Deploy", "deployGetApiV1AppsByAppIDReleasesPromotePreflight"),
  new Route("DELETE", "/api/v1/apps/{appID}/staging", "Deploy", "deployDeleteApiV1AppsByAppIDStaging"),
  new Route("PUT", "/api/v1/apps/{appID}/staging", "Deploy", "deployPutApiV1AppsByAppIDStaging"),
  new Route("GET", "/api/v1/apps/discover", "Apps", "appsGetApiV1AppsDiscover"),
  new Route("GET", "/api/v1/apps/search", "Apps", "appsGetApiV1AppsSearch"),
  new Route("DELETE", "/api/v1/comments/{commentID}", "Apps", "appsDeleteApiV1CommentsByCommentID"),
  new Route("POST", "/api/v1/git/github/complete", "Deploy", "deployPostApiV1GitGithubComplete"),
  new Route("GET", "/api/v1/github/accounts", "deploy", "deployGetApiV1GithubAccounts"),
  new Route("GET", "/api/v1/github/installations/{installationID}/repositories", "deploy", "deployGetApiV1GithubInstallationsByInstallationIDRepositories"),
  new Route("GET", "/api/v1/me", "Auth", "authGetApiV1Me"),
  new Route("GET", "/api/v1/me/apps/owned", "Apps", "appsGetApiV1MeAppsOwned"),
  new Route("GET", "/api/v1/me/apps/received", "Apps", "appsGetApiV1MeAppsReceived"),
  new Route("GET", "/api/v1/me/apps/workspace", "Apps", "appsGetApiV1MeAppsWorkspace"),
  new Route("GET", "/api/v1/me/personal-access-tokens", "Schema", "schemaGetApiV1MePersonalAccessTokens"),
  new Route("POST", "/api/v1/me/personal-access-tokens", "Schema", "schemaPostApiV1MePersonalAccessTokens"),
  new Route("DELETE", "/api/v1/me/personal-access-tokens/{patID}", "Schema", "schemaDeleteApiV1MePersonalAccessTokensByPatID"),
  new Route("GET", "/api/v1/oauth-clients/{clientID}", "Auth", "authGetApiV1OauthClientsByClientID"),
  new Route("DELETE", "/api/v1/oauth/clients/{clientID}/grants/me", "Auth", "authDeleteApiV1OauthClientsByClientIDGrantsMe"),
  new Route("GET", "/api/v1/templates", "Apps", "appsGetApiV1Templates"),
  new Route("GET", "/api/v1/tenants", "Tenants", "tenantsGetApiV1Tenants"),
  new Route("GET", "/api/v1/tenants/{tenantID}", "Tenants", "tenantsGetApiV1TenantsByTenantID"),
  new Route("POST", "/api/v1/tenants/{tenantID}/app-bootstraps", "Deploy", "deployPostApiV1TenantsByTenantIDAppBootstraps"),
  new Route("GET", "/api/v1/tenants/{tenantID}/app-bootstraps/{bootstrapID}", "Deploy", "deployGetApiV1TenantsByTenantIDAppBootstrapsByBootstrapID"),
  new Route("GET", "/api/v1/tenants/{tenantID}/apps", "Apps", "appsGetApiV1TenantsByTenantIDApps"),
  new Route("POST", "/api/v1/tenants/{tenantID}/apps", "Apps", "appsPostApiV1TenantsByTenantIDApps"),
  new Route("GET", "/api/v1/tenants/{tenantID}/apps/check-availability", "Apps", "appsGetApiV1TenantsByTenantIDAppsCheckAvailability"),
  new Route("GET", "/api/v1/tenants/{tenantID}/connectors", "Gateway", "gatewayGetApiV1TenantsByTenantIDConnectors"),
  new Route("GET", "/api/v1/tenants/{tenantID}/connectors/{connectorID}", "Gateway", "gatewayGetApiV1TenantsByTenantIDConnectorsByConnectorID"),
  new Route("POST", "/api/v1/tenants/{tenantID}/connectors/{connectorID}/discover", "Gateway", "gatewayPostApiV1TenantsByTenantIDConnectorsByConnectorIDDiscover"),
  new Route("GET", "/api/v1/tenants/{tenantID}/connectors/{connectorID}/resources", "Gateway", "gatewayGetApiV1TenantsByTenantIDConnectorsByConnectorIDResources"),
  new Route("GET", "/api/v1/tenants/{tenantID}/deployments", "Deploy", "deployGetApiV1TenantsByTenantIDDeployments"),
  new Route("GET", "/api/v1/tenants/{tenantID}/discover/apps", "Apps", "appsGetApiV1TenantsByTenantIDDiscoverApps"),
  new Route("POST", "/api/v1/tenants/{tenantID}/gateway/document-invoke", "Gateway", "gatewayPostApiV1TenantsByTenantIDGatewayDocumentInvoke"),
  new Route("POST", "/api/v1/tenants/{tenantID}/gateway/file-invoke", "Gateway", "gatewayPostApiV1TenantsByTenantIDGatewayFileInvoke"),
  new Route("POST", "/api/v1/tenants/{tenantID}/gateway/invoke", "Gateway", "gatewayPostApiV1TenantsByTenantIDGatewayInvoke"),
  new Route("POST", "/api/v1/tenants/{tenantID}/gateway/query", "Gateway", "gatewayPostApiV1TenantsByTenantIDGatewayQuery"),
  new Route("POST", "/api/v1/tenants/{tenantID}/gateway/sessions", "Gateway", "gatewayPostApiV1TenantsByTenantIDGatewaySessions"),
  new Route("DELETE", "/api/v1/tenants/{tenantID}/gateway/sessions/{sessionID}", "Gateway", "gatewayDeleteApiV1TenantsByTenantIDGatewaySessionsBySessionID"),
  new Route("GET", "/api/v1/tenants/{tenantID}/me/connectors", "Gateway", "gatewayGetApiV1TenantsByTenantIDMeConnectors"),
  new Route("GET", "/api/v1/tenants/{tenantID}/me/connectors/{connectorID}/resources", "Gateway", "gatewayGetApiV1TenantsByTenantIDMeConnectorsByConnectorIDResources"),
  new Route("GET", "/api/v1/tenants/{tenantID}/me/grants", "Authorization", "authorizationGetApiV1TenantsByTenantIDMeGrants"),
  new Route("GET", "/api/v1/users/me/apps", "Apps", "appsGetApiV1UsersMeApps"),
  new Route("POST", "/auth/logout", "Auth", "authPostAuthLogout"),
  new Route("POST", "/auth/refresh", "Auth", "authPostAuthRefresh"),
  new Route("GET", "/config/public", "Config", "configGetConfigPublic"),
  new Route("GET", "/oauth/google/callback", "Gateway", "gatewayGetOauthGoogleCallback"),
  new Route("GET", "/oauth/userinfo", "Auth", "authGetOauthUserinfo")
);

  public static Route byOperation(String operationId) {
    return ALL.stream().filter(route -> route.operationId().equals(operationId)).findFirst().orElseThrow(() -> new IllegalArgumentException("unknown operation " + operationId));
  }
}
